version: '3.8'

services:
  bot:
    image: node:18
    container_name: ava_bot
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./bot/:/usr/src/app
    networks:
      - node-ceticy_default
    env_file:
      - .env
    command: >
      sh -c "npm install && npm run dev"
  web:
    image: node:18
    container_name: ava_web
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./web/:/usr/src/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ava-web.rule=Host(`workshop.ceticy.fr`)"
      - "traefik.http.routers.ava-web.entrypoints=websecure"
      - "traefik.http.routers.ava-web.tls=true"
      - "traefik.http.routers.ava-web.tls.certresolver=myresolver"
      - "traefik.http.services.ava-web.loadbalancer.server.port=3000"
      - "traefik.http.routers.ava-web-http.rule=Host(`workshop.ceticy.fr`)"
      - "traefik.http.routers.web-http.entrypoints=web"
      - "traefik.http.routers.web-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - node-ceticy_default
    env_file:
      - .env
    command: >
      sh -c "npm install && npm run dev"


networks:
  node-ceticy_default:
    external: true
